{
    "name": "Speedtest",
    "version": "1.1.11",
    "icon": "fas fa-user-alien",
    "category": "information",
    "author": "maxbachmann",
    "maintainers": [
        "Psychokiller1888"
    ],
    "desc": "Run internet speed test",
    "aliceMinVersion": "1.0.0-b5",
    "systemRequirements": [],
    "pipRequirements": [
        "speedtest-cli"
    ],
    "conditions": {
        "lang": [
            "en",
            "de",
            "fr"
        ],
        "online": true
    }
}
